#!/bin/bash

set -e  # Exit immediately if a command exits with a non-zero status.

# Set the directory to check
base_dir="/opt/ml/model/"
export SAGEMAKER_BIND_TO_PORT=${SAGEMAKER_BIND_TO_PORT:-8080}

# Check if the directory exists
if [ ! -d "$base_dir" ]; then
    echo "Error: $base_dir directory does not exist"
    exit 1
fi

# Find the first subdirectory in the base directory
model_dir=$(find "$base_dir" -mindepth 1 -maxdepth 1 -type d -print -quit)

# Check if a subdirectory was found
if [ -z "$model_dir" ]; then
    echo "No subdirectory found"
    exit 0
else
    # Set the model_path
    model_path="$model_dir"
    
    echo "Found model directory" $model_dir

    if [ -f "$model_dir/api.py" ]; then
        # If api.py file exists, proceed with setup
        cp -r $base_dir/GPT-SoVITS/* /opt/program/ || { log "Failed to copy GPT-SoVITS data"; exit 1; }
        echo "Copied ${model_dir} files to workspace"

        echo "Contents of /opt/program/:"
        ls -R /opt/program/

        python3 ssh_helper_start.py || { echo "SSH helper start failed";}
        
        # Start api
        python /opt/program/api.py -dr Brigida.wav -dt "hi hello" -dl "zh" -a "0.0.0.0" -p "8080"
    else
        echo "Error: api.py not found in $model_dir"
        exit 1
    fi

fi